dist: trusty

go_import_path: github.com/cloudflare/unsee

jobs:
  include:
    - stage: Test Go code
      language: go
      go:  "1.8.3"
      before_script: nvm install 8
      env:
        - NODE_ENV=test
      cache:
        directories:
          - node_modules
          - vendor
      script: make test-go

    - stage: Test JavaScript code
      language: node_js
      node_js: "8"
      env:
        - NODE_ENV=test
      cache:
        directories:
          - node_modules
      script: make test-js

    - stage: Lint Go code
      language: go
      go:  "1.8.3"
      script: make lint-go

    - stage: Lint JavaScript code
      language: node_js
      node_js: "8"
      cache:
        directories:
          - node_modules
      script: make lint-js

    - stage: Build Docker image
      sudo: true
      before_install:
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
      script: make docker-image
