dist: trusty

jobs:
  include:
    - stage: Lint Go code
      language: go
      go:
        - 1.8.x
      go_import_path: github.com/cloudflare/unsee
      cache:
        directories:
          - vendor
      script: make lint-go

    - stage: Lint JavaScript code
      language: node_js
      node_js:
        - "8"
      env:
        - NODE_ENV=test
      cache:
        directories:
          - node_modules
      script: make lint-js

    - stage: Test Go code
      language: go
      go:
        - 1.8.x
      go_import_path: github.com/cloudflare/unsee
      script: make test-go

    - stage: Test JavaScript code
      language: node_js
      node_js:
        - "8"
      env:
        - NODE_ENV=test
      cache:
        directories:
          - node_modules
      script: make test-js

    - stage: Build Docker image
      sudo: true
      before_install:
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
      script: make docker-image
