sudo: true
dist: trusty

jobs:
  include:
    - stage: Build Docker image
      script: make docker-image

    - stage: Lint Go code
      language: go
      go:
        - 1.8.x
      go_import_path: github.com/cloudflare/unsee
      cache:
        directories:
          - vendor
      script: make lint-go

    - stage: Lint JavaScript code
      language: node_js
      env:
        - NODE_ENV=test
      cache:
        directories:
          - node_modules
      script: make lint-js

    - stage: Test Go code
      language: go
      go:
        - 1.8.x
      go_import_path: github.com/cloudflare/unsee
      cache:
        directories:
          - vendor
      script: make test-go

    - stage: Test JavaScript code
      language: node_js
      env:
        - NODE_ENV=test
      cache:
        directories:
          - node_modules
      script: make test-js
